import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import FontDebugger from "@/components/FontDebugger";
import FontSizeOverlay from "@/components/FontSizeOverlay";
import Navbar from "@/components/Navbar";
import UnitCheatSheet from "@/components/UnitCheatSheet";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" >
      <body>
        <Navbar />

        <main className="p-6">{children}</main>
        
        {/* Persistent Overlay */}
        {/* <FontDebugger /> */}
        <FontSizeOverlay />
        <UnitCheatSheet />
      </body>
    </html>
  );
}

